baseURL: https://optimistic-archimedes.netlify.app/
#baseURL: http://localhost:1313/
languageCode: fr-fr
title: TQA Asciidoc
math: false
s9: false
theme: 
    - antora-default-ui-hugo-theme
    - hugo-cards
#theme: hugo-theme-arch-terminal

markup:
  preserveTOC: false
  workingFolderCurrent: false  # default is false
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute:
        block: false
        title: true
      autoHeadingID: true
      autoHeadingIDType: github
    renderer:
      hardWraps: false
      unsafe: false
      xhtml: false

  asciidocExt:
    preserveTOC: false
    workingFolderCurrent: false  # default is false
    backend: html5
    extensions: []
    failureLevel: fatal
    noHeaderOrFooter: true
    safeMode: safe
    sectionNumbers: false
    trace: false
    verbose: false

    attributes:
      toc: auto
      hide-uri-scheme: true@  # trailing @ means ok to override
      sectlinks: true
      huri-config-vars: https://gohugo.io/getting-started/configuration/
      huri-page-vars: https://gohugo.io/variables/page/
      huri-site-vars: https://gohugo.io/variables/site/
      huri-file-vars: https://gohugo.io/variables/files/
      imagesdir: 
  pandoc:
    mathjax: false
defaultMarkdownHandler: "adoc"

security:
  enableInlineShortcodes: false
  exec:
    allow: ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$', '^asciidoctor$', '^pandoc$']
    osEnv: ['(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$']

  funcs:
    getenv: ['^HUGO_']

  http:
    methods: ['(?i)GET|POST']
    urls: ['.*']
