(function(){var m;function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function ba(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:aa(a)}}function u(a){if(!(a instanceof Array)){a=ba(a);for(var b,c=[];!(b=a.next()).done;)c.push(b.value);a=c}return a}var ca="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},da;
if("function"==typeof Object.setPrototypeOf)da=Object.setPrototypeOf;else{var ea;a:{var fa={a:!0},ha={};try{ha.__proto__=fa;ea=ha.a;break a}catch(a){}ea=!1}da=ea?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var ia=da;
function v(a,b){a.prototype=ca(b.prototype);a.prototype.constructor=a;if(ia)ia(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.vb=b.prototype};function ma(a,b,c,d){this.o=a;this.method=b;this.version=c;this.g=d}function na(a){return!!a&&void 0!==a.omid_message_guid&&void 0!==a.omid_message_method&&void 0!==a.omid_message_version&&"string"===typeof a.omid_message_guid&&"string"===typeof a.omid_message_method&&"string"===typeof a.omid_message_version&&(void 0===a.omid_message_args||void 0!==a.omid_message_args)}function oa(a){return new ma(a.omid_message_guid,a.omid_message_method,a.omid_message_version,a.omid_message_args)}
function pa(a){var b={};b=(b.omid_message_guid=a.o,b.omid_message_method=a.method,b.omid_message_version=a.version,b);void 0!==a.g&&(b.omid_message_args=a.g);return b};function qa(a){this.o=a};function ra(a){for(var b=[],c=0;c<arguments.length;++c)b[c]=arguments[c];ta(function(){return console.error.apply(console,u(b))})}function ta(a){"undefined"!==typeof console&&console&&console.error&&a()};function ua(a,b){if(!b)throw Error("Value for "+a+" is undefined, null or blank.");if("string"!==typeof b&&!(b instanceof String))throw Error("Value for "+a+" is not a string.");if(""===b.trim())throw Error("Value for "+a+" is empty string.");}function va(a){if(!a)throw Error("functionToExecute must not be truthy.");}
function wa(a,b){if(null==b)throw Error(a+" must not be null or undefined.");if("number"!==typeof b||isNaN(b))throw Error("Value for "+a+" is not a number");if(0>b)throw Error(a+" must be a positive number.");};function xa(){return/\d+\.\d+\.\d+(-.*)?/.test("1.3.15-dev")}function ya(){for(var a=["1","3","15"],b=["1","0","3"],c=0;3>c;c++){var d=parseInt(a[c],10),f=parseInt(b[c],10);if(d>f)break;else if(d<f)return!1}return!0};function za(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;return"y"===a?(b&3|8).toString(16):b.toString(16)})};var Aa=eval("this"),y=function(){if("undefined"!==typeof omidGlobal&&omidGlobal)return omidGlobal;if("undefined"!==typeof global&&global)return global;if("undefined"!==typeof window&&window)return window;if("undefined"!==typeof Aa&&Aa)return Aa;throw Error("Could not determine global object context.");}();function Ba(a,b){return a&&(a[b]||(a[b]={}))};function Ca(a){return null!=a&&"undefined"!==typeof a.top&&null!=a.top}function Da(a){if(a===y)return!1;try{if("undefined"===typeof a.location.hostname)return!0}catch(b){return!0}return!1};function Fa(a){this.o=a;this.handleExportedMessage=Fa.prototype.S.bind(this)}v(Fa,qa);Fa.prototype.F=function(a){var b=void 0===b?this.o:b;if(!b)throw Error("Message destination must be defined at construction time or when sending the message.");b.handleExportedMessage(pa(a),this)};Fa.prototype.S=function(a,b){na(a)&&this.g&&this.g(oa(a),b)};function Ga(a,b){this.o=b=void 0===b?y:b;var c=this;a.addEventListener("message",function(d){if("object"===typeof d.data){var f=d.data;na(f)&&d.source&&c.g&&c.g(oa(f),d.source)}})}v(Ga,qa);Ga.prototype.F=function(a){var b=void 0===b?this.o:b;if(!b)throw Error("Message destination must be defined at construction time or when sending the message.");b.postMessage(pa(a),"*")};function Ha(a){try{return a.frames?!!a.frames.omid_v1_present:!1}catch(b){return!1}};var Ia=["omid","v1_VerificationServiceCommunication"],Ja=["omidVerificationProperties","serviceWindow"];function Ka(a,b){return b.reduce(function(c,d){return c&&c[d]},a)};function La(a){if(!a){var b;"undefined"===typeof b&&"undefined"!==typeof window&&window&&(b=window);b=Ca(b)?b:y;var c=void 0===c?Ha:c;a=[];var d=Ka(b,Ja);d&&a.push(d);a.push(Ca(b)?b.top:y);a:{a=ba(a);for(var f=a.next();!f.done;f=a.next()){b:{d=b;f=f.value;var e=c;if(!Da(f))try{var h=Ka(f,Ia);if(h){var g=new Fa(h);break b}}catch(l){}g=e(f)?new Ga(d,f):null}if(d=g){a=d;break a}}a=null}}if(this.g=a)this.g.g=this.ob.bind(this);else if(c=(c=y.omid3p)&&"function"===typeof c.registerSessionObserver&&"function"===
typeof c.addEventListener?c:null)this.o=c;this.xa=this.ya=0;this.F={};this.S=[];this.ga=(c=y.omidVerificationProperties)?c.injectionId:void 0}function Ma(a){var b=G;va(a);b.o?b.o.registerSessionObserver(a,"adloox.com-omid",b.ga):b.na("addSessionListener",a,"adloox.com-omid",b.ga)}m=La.prototype;m.addEventListener=function(a,b){ua("eventType",a);va(b);this.o?this.o.addEventListener(a,b):this.na("addEventListener",b,a)};
function Na(a){var b=G;ua("url",a);y.document&&y.document.createElement?Oa(b,a):b.na("sendUrl",function(){},a)}function Oa(a,b){function c(f){var e=a.S.indexOf(d);0<=e&&a.S.splice(e,1);f&&f()}var d=y.document.createElement("img");a.S.push(d);d.addEventListener("load",c.bind(a,void 0));d.addEventListener("error",c.bind(a,void 0));d.src=b}
function Pa(a,b,c){var d=G;ua("url",a);y.document?Qa(a,b,c):d.na("injectJavaScriptResource",function(f,e){f?(Ra(e,a),b()):(ra("Service failed to load JavaScript resource."),c())},a)}function Qa(a,b,c){var d=y.document,f=d.body;d=d.createElement("script");d.onload=b;d.onerror=c;d.src=a;d.type="application/javascript";f.appendChild(d)}function Ra(a,b){try{eval(a)}catch(c){ra('Error evaluating the JavaScript resource from "'+b+'".')}}
m.setTimeout=function(a,b){va(a);wa("timeInMillis",b);if(Sa())return y.setTimeout(a,b);var c=this.ya++;this.na("setTimeout",a,c,b);return c};m.clearTimeout=function(a){wa("timeoutId",a);Sa()?y.clearTimeout(a):this.bb("clearTimeout",a)};m.setInterval=function(a,b){va(a);wa("timeInMillis",b);if(Ta())return y.setInterval(a,b);var c=this.xa++;this.na("setInterval",a,c,b);return c};m.clearInterval=function(a){wa("intervalId",a);Ta()?y.clearInterval(a):this.bb("clearInterval",a)};
function Sa(){return"function"===typeof y.setTimeout&&"function"===typeof y.clearTimeout}function Ta(){return"function"===typeof y.setInterval&&"function"===typeof y.clearInterval}m.ob=function(a){var b=a.method,c=a.o;a=a.g;if("response"===b&&this.F[c]){var d=xa()&&ya()?a?a:[]:a&&"string"===typeof a?JSON.parse(a):[];this.F[c].apply(this,d)}"error"===b&&window.console&&ra(a)};m.bb=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.na.apply(this,[a,null].concat(u(c)))};
m.na=function(a,b,c){for(var d=[],f=2;f<arguments.length;++f)d[f-2]=arguments[f];this.g&&(f=za(),b&&(this.F[f]=b),d=xa()&&ya()?d:JSON.stringify(d),this.g.F(new ma(f,"VerificationService."+a,"1.3.15-dev",d)))};var Ua=void 0;if(Ua=void 0===Ua?"undefined"===typeof omidExports?null:omidExports:Ua){var Va=["OmidVerificationClient"];Va.slice(0,Va.length-1).reduce(Ba,Ua)[Va[Va.length-1]]=La};var H=this,I=H==H.self;function J(){}function Wa(a,b){a=typeof a;return b?a==b:a}function L(a){return a&&Wa(a,"object")}function Xa(a){return Wa(a,"string")}function M(a){return Wa(a,"number")}function N(a){return Wa(a,"function")}function O(a){return Wa(a,"boolean")}var Ya=I?function(a){return L(a)&&L(a.ownerDocument)&&a instanceof a.ownerDocument.defaultView.HTMLElement}:function(){return!1};function P(a){return M(a)?Math.floor(a):parseInt(a,10)}
function Za(){return(new Date).getTimezoneOffset()}var S=L(H.performance)&&N(H.performance.now)?function(){return P(H.performance.now())}:function(){return(new Date).getTime()+6E4*Za()},$a=S();function ab(a){return(a||[]).reduce(function(b,c,d){return b+d%2*c},0)}function bb(a){return 1<(a||[]).length&&0==a[0]}var cb=new La,G=cb.g||cb.o?cb:!1;function T(a,b){return(G||H).setTimeout(a,b)}function db(a){(G||H).clearTimeout(a)}function eb(a,b){return(G||H).setInterval(a,b)}var fb=!1,gb={},hb=[],ib=0;
function jb(a,b){if(null==b.K||b.K==a.K)try{b.pa.apply(b.context||null,[a.K,a.tb].concat(a.cb))}catch(c){a.K.l("error",{err:c.message,"%b":c.stack})}}function kb(){M(fb)&&db(fb);for(fb=!0;ib<hb.length;ib++)for(var a=hb[ib],b=gb[a.name]||[],c=0;c<b.length;c++)jb(a,b[c]);fb=!1}function lb(a,b,c){for(var d=[],f=2;f<arguments.length;++f)d[f-2]=arguments[f];J.apply(null,["fire",b].concat(u(d)));hb.push({K:a,tb:S(),name:b,cb:d});!0!==fb&&(a&&a.ended?kb():!1===fb&&(fb=T(kb,0)))}
function U(a,b,c,d){gb[b]||(gb[b]=[]);a={K:a,pa:c,context:d};gb[b].push(a);for(c=0;c<ib;c++)d=hb[c],d.name==b&&(J.apply(null,["fire [playback]",d.name].concat(u(d.cb))),jb(d,a))}function mb(a,b,c){for(var d=gb[b]||[],f=d.length;0<f--;){var e=d[f];e.K!=a||e.pa!=c&&e.pa.$a!=c||gb[b].splice(f,1)}}
var nb=I?function(a){var b=H.document.createElement("a");b.href=a;return b}:function(a){var b=/^(([^:/?#]+):)?(\/\/([^/?#]*))?([^?#]*)(\?([^#]*))?(#(.*))?/;a=a.match(b)||"about:blank".match(b);a={protocol:a[1]||"",hostname:a[3]||"//",pathname:a[5]||"/",search:a[6]||"",hash:a[8]||""};a.host=a.hostname.replace(/:[0-9]+$/,"");a.port=P(a.hostname.replace(/^.*:([0-9]+)$/,"$1"));if(isNaN(a.port))switch(a.protocol){case "http":a.port=80;break;case "https":a.port=443;break;default:a.port=0}a.href=a.protocol+
"//"+a.hostname+a.path+a.search+a.hash;a.origin=a.protocol+"//"+a.hostname;return a};function ob(a){return encodeURIComponent(a).replace(/[!'()*]/g,function(b){return"%"+b.charCodeAt(0).toString(16)})}function pb(a){var b={};if(!a.length)return b;a=a.split("&");for(var c=0;c<a.length;c++){var d=a[c].split("=",2);if(d[0].length){var f=decodeURIComponent(d[0]);d=d[1];try{d=decodeURIComponent(d)}catch(e){}d=d||!0;void 0===b[f]?b[f]=[d]:b[f].push(d)}}return b}function qb(a){return a[a.length-1]}var rb;
if(I){var sb;if(!(sb=H.document.currentScript))a:{for(var tb=new RegExp("/"+"tfav_adl_435.js".replace(".","\\.")+"(?:[#?]|$)"),ub=H.document.scripts,vb=ub.length;0<vb--;)if(ub[vb]&&ub[vb].src&&ub[vb].src.match(tb)&&!ub[vb].getAttribute("data-adloox-sid")){sb=ub[vb];break a}sb=null}rb=sb}else rb=void 0;var V=rb,xb=V?nb(V.src):void 0;
function yb(a){var b=this;this.A=a;this.u=this.v=this.g=null;this.o={};this.F=this.W=this.fa=null;a.subscribe("rollstate.visi.run",function(){b.F=!0});a.subscribe("rollstate.visi.pause",function(){b.F=!1});this.J=this.duration=this.ca=void 0;this.za=this.oa=null;this.data=this.R.bind(this);a.subscribe("adunit",this.S,this)}yb.prototype.Ja=function(){var a=!1,b;for(b in this.o){var c=this.o[b];a=a||c.U;if(c.ratio<this.u.L.ba||c.L||c.state)return!1}return a?!0:void 0};
yb.prototype.Ka=function(){if(this.u.C){var a=!1,b;for(b in this.o){var c=this.o[b];a=a||c.U;if(c.ratio<(this.u.C.ba||NaN)||c.C||c.state)return!1}return a?!0:void 0}};
yb.prototype.S=function(a,b,c){function d(k){!l&&c.video?zb(e,k,c):!l&&Ya(c.slot)?Ab(k,c):k.l("rollstate.visi.run")}function f(k){e.g=k||null;!e.g&&e.v&&e.A.D.wa&&(e.g=e.A.D.wa(e.v));e.g&&(e.u.L.j={x:P(e.g.width*Math.sqrt(e.u.L.ba)/2),y:P(e.g.height*Math.sqrt(e.u.L.ba)/2)},e.u.C&&(e.u.C.j={x:P(e.g.width*Math.sqrt(e.u.C.ba)/2),y:P(e.g.height*Math.sqrt(e.u.C.ba)/2)}));a.l("visi.rect",e.g)}var e=this,h=.5,g=1E3;switch(a.m.creatype){case 6:case 23:this.W=200;g=2E3;break;default:this.W=100,!this.A.D.s.Sa&&
this.g&&242500<=this.g.width*this.g.height&&(h=.3)}this.u={L:{ba:Math.max(h,(a.m.custom1area||0)/100),time:Math.max(g,1E3*(a.m.custom1sec||0))}};a.da=Math.min(a.da,this.u.L.time);a.m.custom2area&&a.m.custom2sec&&(this.u.C={ba:a.m.custom2area/100,time:1E3*a.m.custom2sec},a.da=Math.min(a.da,this.u.C.time));Ya(c.slot)&&(c.slot.setAttribute("data-adloox-type","slot"),c.slot.setAttribute("data-adloox-sid",a.N),this.v=c.slot);Ya(c.video)&&(c.video.setAttribute("data-adloox-type","video"),c.video.setAttribute("data-adloox-sid",
a.N),this.v=c.video);a.subscribe("geometry",function(k,q,n){f(n)});f(c.rect);Bb(this);var l=1==this.A.m.creatype;a.j.size=function(){var k=e.g;return null===k?void 0:k.width+"x"+k.height};a.j.pdv=function(){return e.ca};a.j.ad=function(){return e.duration};a.j.ad2=function(){return e.J};a.j.p_d_v=function(){return ab(e.ca)/1E3};a.j.a_d=function(){return ab(e.duration)/1E3};a.j.wasatf=function(){return 2*~~bb(e.duration)};a.j.visible=function(){return 2*~~e.oa};l?(a.j.wasatf=2,a.j.a_d2=function(){return ab(e.ca)/
1E3},a.j.wasatf2=2,a.j.visible2=function(){return 2*~~(2E3<=ab(e.ca))}):this.u.C&&(a.j.a_d2=function(){return ab(e.J)/1E3},a.j.wasatf2=function(){return 2*~~bb(e.J)},a.j.visible2=function(){return 2*~~e.za});a.j.d9=function(){var k=[],q;for(q in e.o)k.push(q);return k};this.F=!1;a.ra&&a.m.targetelt.length&&"hidden"==this.v.style.visibility?a.subscribe("fw",d):d(a,b)};
function zb(a,b,c){function d(){b.l("rollstate.visi.run")}c.video.addEventListener("playing",d,b.D.s.H?!1:{passive:!0});c.video.addEventListener("pause",function(){b.l("rollstate.visi.pause")},b.D.s.H?!1:{passive:!0});if(!c.video.paused&&3<=c.video.readyState)d();else var f=eb(function(){a.F?(G||H).clearInterval(f):0<c.video.currentTime&&d()},200)}
function Ab(a,b){a.P[2]=S();var c=0;a.P[3]=0;var d=[].concat(u(b.slot.getElementsByTagName("*")));d.push(b.slot);var f=[];d.forEach(function(e){var h="";switch(e.tagName){case "IMG":e.src&&(h=e.src);break;default:var g=L(e.style)&&e.style["background-image"];g&&(g=g.match(/^url\("?([^")]+)"?\)$/))&&(h=g[1])}if(/^https?:/.test(h)&&"none"!=e.style.display&&"none"!=e.style.visibility){a.P[3]+=1;var l=function(){l=J;--c||(a.P[5]=S(),a.l("rollstate.visi.run"))};g=function(q,n){l(q,n)};var k="IMG"==e.tagName?
e:new Image;k.onload=k.onerror=g;"IMG"!=e.tagName&&(k.src=h);k.complete||4===k.readyState||0<k.naturalWidth?l=J:(c++,f.push(g))}});(a.P[4]=c)||(a.P[5]=S());c?T(function(){f.forEach(function(e){return e(null,!0)})},2E3):a.l("rollstate.visi.run")}
function Bb(a){function b(e){if(null!==e[0]&&null!==e[1]&&null!==e[2])return e[1]&&(e[0]||e[2])}var c=[];a.A.P[9]=0;a.A.subscribe("impression",function(e){function h(){h=J;k.za=!0;e.l("viewable.custom")}function g(){g=J;k.oa=!0;e.l("viewable.iab")}function l(t,p,w){if(!e.ma)return w;w||(w=[0]);w.length%2==~~t&&w.push(0);w[w.length-1]+=p;return w}var k=this,q=S(),n=eb(function(){var t=S()-q;q+=t;c.forEach(function(w){return w()});k.ca=l(!0,t,k.ca);e.P[9]+=k.A.D.hidden?0:t;if(k.fa){var p=k.Ja();O(p)&&
(k.duration=l(p,t,k.duration),p&&k.duration&&0==k.duration.length%2&&k.duration[k.duration.length-1]>k.u.L.time&&g());p=k.Ka();O(p)&&(k.J=l(p,t,k.J),p&&k.J&&0==k.J.length%2&&k.J[k.J.length-1]>k.u.C.time&&h())}},this.W);e.subscribe("end",function(){(G||H).clearInterval(n)})},a);var d=1==a.A.m.creatype,f;(function(){I&&"mraid"!=a.A.D.type&&a.A.D.s.ea&&!a.A.D.s.sa&&c.push(function(){a.R({id:"focus",state:a.A.D.Ea})})})();(function(){I&&-1==["mraid","omid"].indexOf(a.A.D.type)&&c.push(function(){a.R({id:"page",
state:a.A.D.hidden})})})();(function(){function e(){a.R({id:"takeover",U:!0,state:Cb(W(a.v)).y>Db(a.v).height})}I&&d&&a.v&&(a.A.subscribe("geometry",e),e())})();(function(){if(I&&!d&&a.v){var e=[a.u.L.ba];a.u.C&&e.push(a.u.C.ba);try{f=new IntersectionObserver(function(h){a.R({id:"intersection",U:!0,ratio:h[0].intersectionRatio})},{threshold:e}),a.R({id:"intersection",$:!1}),f.observe(a.v),a.A.subscribe("end",f.disconnect.bind(f))}catch(h){}}})();(function(){function e(){e=function(){var h=NaN;if(a.g){h=
a.v;for(var g=a.g,l=g.width,k=g.height;h;){var q=Db(h);l=Math.max(Math.min(l,l-Math.abs(Math.min(0,g.left))-Math.abs(Math.min(0,q.width-g.right))),0);k=Math.max(Math.min(k,k-Math.abs(Math.min(0,g.top))-Math.abs(Math.min(0,q.height-g.bottom))),0);(h=a.A.D.frameElement(h))&&(g=a.A.D.wa(h))}h=l*k/(a.g.width*a.g.height)}a.R({id:"classic",U:!0,ratio:h})};e()}I&&!d&&a.v&&!f&&(a.R({id:"classic",$:!1}),a.A.subscribe("visi.rect",function(){e()}))})();(function(){function e(){var h={id:"element",U:!0},g=a.v.ownerDocument,
l=[a.g.left+P(a.g.width/2),a.g.top+P(a.g.height/2)],k=!g.elementFromPoint(l[0],l[1]);h.L=b([!g.elementFromPoint(l[0]-a.u.L.j.x,l[1]-a.u.L.j.y),k,!g.elementFromPoint(l[0]+a.u.L.j.x,l[1]+a.u.L.j.y)]);a.u.C&&(h.C=b([!g.elementFromPoint(l[0]-a.u.C.j.x,l[1]-a.u.C.j.y),k,!g.elementFromPoint(l[0]+a.u.C.j.x,l[1]+a.u.C.j.y)]));a.R(h)}I&&!d&&a.v&&!f&&!a.A.D.s.ea&&a.A.D.s.H&&c.push(e)})();(function(){function e(k){e.hidden[k.i]=k.h;k={id:"animation",$:e.hidden.every(function(q){return void 0!==q}),U:!0};k.L=
b([e.hidden[0],e.hidden[2],e.hidden[1]]);a.u.C&&(k.C=b([e.hidden[3],e.hidden[2],e.hidden[4]]));a.R(k)}e.pb=function(){function k(t){e.hidden[t]=void 0;var p=n.createElement("iframe");p.style.position="absolute";p.style["pointer-events"]="none";p.style["z-index"]=e.eb+1;p.style["border-style"]="none";p.style["background-color"]="transparent";p.style.width=p.style.height="8px";if(2==t)p.style.top=p.style.left="50%";else{var w=50-P(100*(3<=t?a.u.C:a.u.L).j.x/a.g.width)+"%";t%3?p.style.top=p.style.left=
w:p.style.bottom=p.style.right=w}w=n.createElement("html");var C=n.createElement("head"),r=n.createElement("script");r.innerText="var l, w, h = null, f = function(n){ clearTimeout(w); var hh = n ? n - l > "+Math.floor(.9*a.W)+" : true; if (h != hh) { h = hh; parent.postMessage({ i: "+t+", h: h }, '*') }; if (n) setTimeout(q, "+a.W+") }, q = function(){ l = performance.now(); w = setTimeout(f, "+a.W+"); requestAnimationFrame(f) }; onload = q";C.appendChild(r);w.appendChild(C);p.sandbox="allow-scripts";
p.srcdoc=w.outerHTML;p.onload=function(){e.sources[t]=p.contentWindow};n.body.appendChild(p)}e.sources=[];e.hidden=[];var q=e.proxy.contentWindow,n=q.document;q.onmessage=function(t){e.sources.forEach(function(p){p===t.source&&e(t.data)})};for(q=0;q<3+(a.u.C?2:0);q++)k(q);a.A.subscribe("visi.rect",function(){var t=Cb(W(a.v)),p=e.proxy.style;p.top=P(a.g.top+t.y)+"px";p.left=P(a.g.left+t.x)+"px";p.width=a.g.width+"px";p.height=a.g.height+"px"})};if(I&&!d&&a.v&&!f&&(!a.A.D.s.ea||a.A.D.s.sa)&&N(H.requestAnimationFrame)&&
!a.A.D.s.H){a.R({id:"animation",$:!1});var h=W(a.v).document;e.proxy=h.createElement("iframe");e.proxy.setAttribute("data-adloox-type","proxy");e.proxy.setAttribute("data-adloox-sid",a.A.N);var g=function(){T(function(){if(e.proxy){try{e.proxy.parentNode.removeChild(e.proxy)}catch(k){}delete e.proxy}},0)};e.proxy.onload=function(){try{e.proxy.contentWindow.document&&e.pb()}catch(k){g(),this.R({id:"animation",$:!0,state:!1})}};var l=W(e.proxy).getComputedStyle(e.proxy);e.eb=P(l.getPropertyValue("z-index")||
0)-1E3;l=e.proxy.style;l.position="absolute";l["pointer-events"]="none";l["z-index"]=e.eb;l["border-style"]="none";l["background-color"]="transparent";h.body.appendChild(e.proxy);a.A.subscribe("end",g)}})();a.A.P[6]=S();a.A.subscribe("visi.booted",function(e){e.P[7]=S()});a.fa=!1;Eb(a)}yb.prototype.R=function(a){this.o[a.id]=a;!1===this.fa&&Eb(this)};function Eb(a){var b=!0,c;for(c in a.o)b=b&&!1!==a.o[c].$;b&&(a.fa=!0,a.oa=!1,a.za=!1,a.A.l("visi.booted"))}
function Fb(a){var b=this;this.A=a;this.u=this.v=null;this.g={};this.o=this.W=this.fa=null;a.subscribe("rollstate.audio.run",function(){b.o=!0});a.subscribe("rollstate.audio.pause",function(){b.o=!1});this.J=this.duration=void 0;this.Ba=this.Aa=null;this.data=this.R.bind(this);a.subscribe("adunit",this.F,this)}Fb.prototype.Ja=function(){var a=!1,b;for(b in this.g){var c=this.g[b];a=a||c.U;if(c.muted||c.ratio<this.u.L.volume||c.L||c.state)return!1}return a?!0:void 0};
Fb.prototype.Ka=function(){if(this.u.C){var a=!1,b;for(b in this.g){var c=this.g[b];a=a||c.U;if(c.muted||c.ratio<(this.u.C.volume||NaN)||c.C||c.state)return!1}return a?!0:void 0}};
Fb.prototype.F=function(a,b,c){function d(g){f.v?Gb(f,g):g.l("rollstate.audio.run")}var f=this,e=Number.MIN_VALUE;switch(a.m.creatype){case 6:case 23:this.W=200;break;default:this.W=100}this.u={L:{volume:Math.max(e,(a.m.custom1vol||0)/100),time:Math.max(2E3,1E3*(a.m.custom1volsec||0))}};a.da=Math.min(a.da,this.u.L.time);a.m.custom2vol&&a.m.custom2volsec&&(this.u.C={volume:a.m.custom2vol/100,time:1E3*a.m.custom2volsec},a.da=Math.min(a.da,this.u.C.time));if(Ya(c.slot)){c.slot.setAttribute("data-adloox-type",
"slot");c.slot.setAttribute("data-adloox-sid",a.N);e=[c.slot].concat(u(c.slot.getElementsByTagName("*")));for(var h=0;h<e.length;h++)if(O(e[h].muted)&&M(e[h].volume)&&N(e[h].addEventListener)){this.v=e[h];break}}Ya(c.video)&&M(c.video.volume)&&(c.video.setAttribute("data-adloox-type","video"),c.video.setAttribute("data-adloox-sid",a.N),this.v=c.video);Hb(this);a.j.aud=function(){return f.duration};a.j.aud2=function(){return f.J};this.o=!1;a.ra&&a.m.targetelt.length&&1==(this.v||{}).defaultMuted?a.subscribe("fw",
d):d(a,b)};
function Gb(a,b){function c(f){b.audio.data({id:"audio",U:!0,ratio:f.volume,muted:f.muted})}function d(){b.l("rollstate.audio.run")}a.v.addEventListener("playing",d,b.D.s.H?!1:{passive:!0});a.v.addEventListener("pause",function(){b.l("rollstate.audio.pause")},b.D.s.H?!1:{passive:!0});a.v.addEventListener("volumechange",function(f){f=f.target;a.o&&f.muted?b.l("rollstate.audio.pause"):a.o||f.muted||b.l("rollstate.audio.run");c(f)},b.D.s.H?!1:{passive:!0});c(a.v);!a.v.paused&&3<=a.v.readyState&&!a.v.muted&&
d()}
function Hb(a){a.A.subscribe("impression",function(b,c){function d(){d=J;h.Ba=!0;b.l("audible.custom")}function f(){f=J;h.Aa=!0;b.l("audible.iab")}function e(g,l,k){if(!b.ma)return k;k||(k=[0]);k.length%2==~~g&&k.push(0);k[k.length-1]+=l;return k}var h=this;b.subscribe("audio.booted",function(g,l){var k=this;this.Ba=this.Aa=!1;l=Math.max(c,l);var q=eb(function(){var n=S()-l;l+=n;var t=k.Ja();O(t)&&(k.duration=e(t,n,k.duration),t&&k.duration&&0==k.duration.length%2&&k.duration[k.duration.length-1]>
k.u.L.time&&f());t=k.Ka();O(t)&&(k.J=e(t,n,k.J),t&&k.J&&0==k.J.length%2&&k.J[k.J.length-1]>k.u.C.time&&d())},this.W);g.subscribe("end",function(){(G||H).clearInterval(q)})},this)},a);a.fa=!1;Ib(a)}Fb.prototype.R=function(a){this.g[a.id]=a;!1===this.fa&&Ib(this)};function Ib(a){var b=!0,c;for(c in a.g)b=b&&!1!==a.g[c].$;b&&(a.fa=!0,a.A.l("audio.booted"))}
function Jb(a,b){this.ua="__"+a+"api";this.ga="tcf"==a?2:1;this.o=b;this.g=null;if("function"==typeof H[this.ua])b=H[this.ua];else a:{b=H;do{b=b.parent;var c=void 0;try{c=b.frames[this.ua+"Locator"]}catch(d){}if(c){b=Kb(c.parent);break a}}while(b!=H.top);b=this.S}this.g=b;this.F="get"+("tcf"==a?"TC":"USP")+"Data";this.ib=2E3}function Lb(a,b){b=[a.F,a.ga,b];a.o&&b.push([a.o]);a.g.apply(null,b)}Jb.prototype.S=function(a,b,c){c({msg:"CMP not found"},!1)};
function Kb(a){var b={},c={};H.addEventListener("message",function(d){var f=this.ua+"Return",e=d.data[f]&&d.data[f].callId;e in b&&(db(c[e]),delete c[e],b[e](d.data[f].returnValue,d.data[f].success),delete b[e])},!1);return function(d,f,e,h){var g=Math.random().toString(16).substr(2);b[g]=e;c[g]=T(function(){e({msg:"CMP deadline"});delete b[g];delete c[g]},this.ib);var l={};l[this.ua+"Call"]={command:d,parameter:h,version:f,callId:g};a.postMessage(l,"*")}}
function Mb(a,b){var c=this;this.D=a;this.P=[$a];this.data=null;a=Xa(b)?[b]:[];xb&&(xb.hash&&a.push(xb.hash.slice(1)),xb.search&&a.push(xb.search.slice(1)));M(H.adloox_pc_viewed)&&a.push("custom2area="+H.adloox_pc_viewed);M(H.adloox_time_viewed)&&a.push("custom2sec="+H.adloox_time_viewed);Xa(H.adloox_target)&&a.push("targetelt="+H.adloox_target);var d=pb(a.join("&"));this.m=d;a=[];for(var f in d)if(d[f]=d[f].filter(function(g){return!!g.length}),d[f].length)if(b=qb(d[f]),f.match(/^id[0-9]+$/)){var e=
P(f.substr(2));0<e&&(d[f]=a[e]=b)}else switch(f){case "fwtype":b=P(b);d[f]=1<=b&&4>=b?b:1;break;case "creatype":case "platform":case "tagid":case "custom1area":case "custom2area":case "custom1vol":case "custom2vol":d[f]=P(b);0<d[f]||delete d[f];break;case "custom1sec":case "custom2sec":case "custom1volsec":case "custom2volsec":d[f]=parseFloat(b);0<d[f]||delete d[f];break;case "ping":d[f]=P(b);isNaN(d[f])&&delete d[f];break;case "id":case "vast":case "url":case "urlt":case "urle":d[f]=b;break;case "client":delete d[f];
break;case "vast_skiptracking":d[f]=!0}else delete d[f];a[20]=a[20]||3821775;d.client="weboramafr";d.creatype||(d.creatype=2);d.targetelt||(d.targetelt=[]);for(f=d.targetelt.length;0<f--;)d.targetelt[f].length||d.targetelt.splice(f,1);f=1==d.creatype;d.fwtype=f?2:d.fwtype||1;this.da=Infinity;this.j={};"russia"==a[12]&&(d.fwtype=2);if(d.url||d.urlt)d.fwtype=4;d.url||(d.url="https://data00.adlooxtracking.com/ads");d.urlt||(d.urlt=d.url+"/ic5.php");d.urle||(d.urle=d.url+"/err.php");d.transaction_id=
H.tab_adloox_transaction_id_weboramafr instanceof Array?H.tab_adloox_transaction_id_weboramafr[0]:d.transaction_id;this.ra=!f&&!(2==d.fwtype||4==d.fwtype);this.g=null;this.N=d.id||Math.floor(1E11*Math.random()+1).toString();this.subscribe=U.bind(this,this);this.unsubscribe=mb.bind(this,this);this.l=lb.bind(this,this);this.start=this.nb.bind(this);this.end=this.Ta.bind(this);this.Ca=this.hb.bind(this);this.ma=null;this.subscribe("rollstate.run",function(){c.ma=!0});this.subscribe("rollstate.pause",
function(){c.ma=!1});this.ended=this.Qa=!1;this.O={sm:this.D.type};this.I=new yb(this);this.audio=new Fb(this);this.o=null;switch(d.fwtype){case 2:f="log";break;case 3:f="wl";break;default:f=d.fwtype}this.l("config");this.j.adloox_io=1;this.j.client=d.client;this.j.campagne="435";this.j.banniere="0";this.j.visite_id=this.N;this.j.seq=function(){var g=0;return function(){return g++}}();this.j.timezone=Za;this.j.js="tfav_adl_435.js";this.j.date_regen="2021-07-06 09:08:16";this.j.plat=d.platform;this.j.tagid=
d.tagid;this.j.fw=f;this.j.version=d.fwtype;this.j.type_crea=function(){return d.creatype};this.j.sl=function(){var g=[],l;for(l in c.O){var k=void 0;try{k=JSON.stringify(c.O[l])}catch(q){k="null"}g.push(['"'+l+'"',k].join(":"))}return g.length?g:void 0};for(f=1;21>f;f++)void 0!==a[f]&&(this.j["id"+f]=a[f]);this.j.p_d=function(){return(S()-$a)/1E3};this.j.d5=function(){return c.P};a={px_imp:"impression",px_view:"viewable.iab",px_viewc:"viewable.custom"};for(var h in a)this.subscribe(a[h],function(g){for(var l=
(d[g]||[]).length;0<l--;)this.l("send",d[g][l])}.bind(this,h));this.subscribe("send.visi",this.La,this);this.subscribe("start",function(){c.m.ping&&c.subscribe("impression",c.jb,c);c.l("send.tracked",c.m.urlt,c.j)});this.subscribe("end",function(){c.La(!0);var g;for(g=(d.bridge||[]).length;0<g--;)c.l("send",d.bridge[g]);if(O(c.ma)){var l;null===c.I.oa?l="px_viewu":!1===c.I.oa&&(l="px_viewn");for(g=(d[l]||[]).length;0<g--;)c.l("send",d[l][g])}});this.subscribe("adunit",function(g){c.P[1]=S();T(function(){function l(){l=
J;c.ma=!0;g.l("impression")}var k=null;g.I.v?k="visi":g.audio.v&&(k="audio");k?g.subscribe("rollstate."+k+".run",function(){l()}):l()},0)})}m=Mb.prototype;m.nb=function(){function a(){b.Qa=!0;b.l("start")}var b=this,c=T(function(){this.Ta()}.bind(this),117E4);this.subscribe("end",function(){db(c)});this.D.Ma?U(null,"manager.booted",a):a()};m.Ta=function(){this.ended||(this.ended=!0,this.P[8]=S(),this.l("end"))};m.hb=function(a,b){this.m[a]=(this.m[a]||[]).concat(b)};
m.jb=function(){function a(){b.ended||(d=T(function(){b.La();c=!0;a()},Math.floor(1E3*(c?f+f/4*Math.random():e+.5+2*Math.random()))),f=Math.min(64,2*Math.max(f,1)))}var b=this,c,d,f=1,e=this.da/1E3;a();this.subscribe("viewable.iab",function(){db(d);e=-.5;f=0;a()})};m.La=function(a){if(this.Qa&&(!this.ended||a)&&!this.g){var b=S();!a&&500>b-this.o||(this.o=b,this.l("send",this.m.urlt,this.j))}};
function X(a){this.type=a||"base";this.xa=!1;this.Ma=1;this.V={};this.Ea=this.hidden=null;this.s={};this.ga=this.fb.bind(this);this.g=this.gb.bind(this);U(null,"fw",this.ta,this);U(null,"send.tracked",this.mb,this);U(null,"send",this.kb,this);U(null,"error",this.lb,this)}m=X.prototype;m.fb=function(){this.Ma++};m.gb=function(){--this.Ma||lb(null,"manager.booted")};m.ta=function(a,b,c){a.g=c.state;a.g&&a.end()};m.kb=function(a,b,c,d){this.ja(a,c,d)};m.ja=function(){throw"__send unsupported";};
m.mb=function(a,b,c,d){this.Ha(a,c,d)};m.Ha=function(){throw"__send_tracked unsupported";};m.lb=function(a,b,c){this.xa||(this.xa=!0,c.client="weboramafr"+(a.m.client?":"+a.m.client:""),c.js="tfav_adl_435.js",c.visite_id=a?a.N:0,this.ja(a,a.m.urle,c));this.xa=!1};
m.url=function(a,b,c){var d=1==a.m.creatype;N(b)&&(b=b());if(Xa(b)&&b==b.trim()){if(c){var f=[],e;for(e in c)if(c.hasOwnProperty(e)&&void 0!==c[e]){var h=c[e];h instanceof Array||(h=[h]);for(var g=0;g<h.length;g++){var l=N(h[g])?h[g]():h[g];void 0!==l&&f.push(ob(e)+"="+ob(l))}}c=f.join("&")}else c=null;b+=c?(-1==b.indexOf("?")?"?":"&")+c:"";return b.split("[ADL_SID]").join(a?a.N:0).split("[ADL_TYPE]").join(a?a.I.v?"vis":a.audio.v?"aud":"???":"").split("[ADL_IMP]").join(~~(a&&O(a.ma))).split("[ADL_VW]").join(a&&
O(a.I.oa)?~~a.I.oa:"").split("[ADL_VWC]").join(a?d?~~(2E3<=ab(a.I.ca)):O(a.I.za)?~~a.I.za:"":"").split("[ADL_ATF]").join(a&&void 0!==a.I.duration?~~bb(a.I.duration):"").split("[ADL_AD]").join(a&&O(a.audio.Aa)?~~a.audio.Aa:"").split("[ADL_ADC]").join(a&&O(a.audio.Ba)?~~a.audio.Ba:"").split("[ADL_DP]").join(a&&void 0!==a.I.ca?a.I.ca:"").split("[ADL_DV]").join(a&&void 0!==a.I.duration?a.I.duration:"").split("[ADL_DVC]").join(a&&void 0!==a.I.J?a.I.J:"").split("[ADL_DA]").join(a&&void 0!==a.audio.duration?
a.audio.duration:"").split("[ADL_DAC]").join(a&&void 0!==a.audio.J?a.audio.J:"").split("[ADL_FW]").join(a&&O(a.g)?~~a.g:"").split("[ERRORCODE]").join(901).split(/(?:\[|$\{|%%)(?:RANDOM|CACHEBUST[A-Z]*)(?:\]|\}|%%)/i).join(Math.floor(99E6*Math.random()+1E6)).split(/\[TIMESTAMP\]/i).join(ob((new Date).toISOString()))}};
function Y(a){function b(){for(var e in d.V)d.V[e].Qa&&d.V[e].l("send.visi")}function c(){for(var e in d.V)d.V[e].end()}X.call(this,a);var d=this;this.s=Nb(this);H.addEventListener("beforeunload",c,this.s.H?!0:{capture:!0,passive:!0});H.addEventListener("onpagehide"in H?"pagehide":"unload",function(e){if(e.persisted)return b();c()},this.s.H?!0:{capture:!0,passive:!0});this.hidden="hidden"==H.document.visibilityState;this.S=!this.hidden;H.document.addEventListener("visibilitychange",function(){d.hidden=
"hidden"==H.document.visibilityState;d.S=d.S||!d.hidden;"unloaded"==H.document.visibilityState?c():d.hidden&&b()},this.s.H?!1:{passive:!0});this.s.ea&&!this.s.sa&&"mraid"!=a&&(this.Ea=!H.top.document.hasFocus(),H.top.addEventListener("focus",function(){d.Ea=!1},this.s.H?!1:{passive:!0}),H.top.addEventListener("blur",function(){d.Ea=!0},this.s.H?!1:{passive:!0}));U(null,"adunit",function(e,h,g){function l(){e.ended||l.Ya||(l.Ya=!0,T(function(){l.Ya=!1;e.l("geometry")},200))}if(g.video||g.slot)(g.video||
g.slot).addEventListener("mouseenter",l,d.s.H?!1:{passive:!0}),(g.video||g.slot).addEventListener("mouseleave",l,d.s.H?!1:{passive:!0});for(h=g.video&&W(g.video)||g.slot&&W(g.slot)||H;;)try{h.addEventListener("resize",l,d.s.H?!1:{passive:!0});h.addEventListener("scroll",l,d.s.H?!1:{passive:!0});if(h==H.top)break;h=h.parent}catch(k){break}});U(null,"config",function(e){Ob(e.m.url);for(var h=(e.m.bridge||[]).length;0<h--;)Ob(e.m.bridge[h]);"ping"in e.m||!(d.hidden||d.s.Sa||d.s.sa)||"vpaid"==a||(e.m.ping=
1)});U(null,"impression",function(e){(e.m.js_imp||[]).forEach(function(h){var g=H.document.createElement("iframe");g.style.display="none";g.src="javascript:false";g.onload=function(){var l=g.contentWindow.document.createElement("script");l.src=d.url(e,h);g.contentWindow.document.head.appendChild(l)};Pb(g,V);e.subscribe("end",function(){g.parentNode.removeChild(g)})});(e.m.html_imp||[]).forEach(function(h){var g=H.document.createElement("iframe");g.style.display="none";g.src=h;Pb(g,V);e.subscribe("end",
function(){g.parentNode.removeChild(g)})})});N(H.navigator.getUserAgent)&&(this.ga(),H.navigator.getUserAgent().then(function(e){U(null,"config",function(h){for(var g in e)Xa(e[g])&&e[g].length&&(h.j["ch_ua_"+g]=e[g])});d.g()}));var f=new Jb("tcf",93);this.ga();Lb(f,function(e,h){U(null,"config",function(g){g.j.tc=O(h)&&L(e)?e.tcString:""});d.g()});f=new Jb("usp");this.ga();Lb(f,function(e,h){U(null,"config",function(g){g.j.usp=O(h)&&L(e)?e.uspString:""});d.g()})}v(Y,X);
function Cb(a){var b=a.document;b=b.documentElement||b.body.parentNode||b.body;var c=void 0!==a.pageXOffset;return{x:P(c?a.pageXOffset:b.scrollLeft),y:P(c?a.pageYOffset:b.scrollTop)}}function W(a){a=a.ownerDocument;return!!a&&(a.defaultView||a.parentWindow)}function Db(a){var b=W(a);a=a.ownerDocument.documentElement;return{width:Math.max(a.clientWidth,b.innerWidth||0),height:Math.max(a.clientHeight,b.innerHeight||0)}}m=Y.prototype;m.frameElement=function(a){a.ownerDocument&&(a=W(a));try{return a.frameElement}catch(b){return null}};
m.wa=function(a){var b=null;try{b=a.getBoundingClientRect(),b={left:P(b.left),right:P(b.right),top:P(b.top),bottom:P(b.bottom)},b.width=b.right-b.left,b.height=b.bottom-b.top}catch(c){}return b};
function Nb(a){var b={};b.rb=!!H.InstallTrigger;b.sb=/Apple/.test(H.navigator.vendor)&&!/CriOS|FxiOS/.test(H.navigator.userAgent);b.ab=!!H.opera;b.qb=!b.ab&&!!H.chrome;b.H="documentMode"in H.document;b.ub=!b.H&&/Edge?\/[1-9]/.test(H.navigator.userAgent);b.Sa=/Android|webOS|iP(?:hone|od|ad)|BlackBerry|mobi|Opera Mini/i.test(H.navigator.userAgent);b.sa=/Version\/[0-9.]+ Chrome\/[0-9.]+ Mobile|iP(?:hone|od|ad).*AppleWebKit(?!.*Version\/[0-9.]+)|; wv/.test(H.navigator.userAgent);b.Ga=H!=H.top;try{b.ea=
!!H.top.document}catch(d){b.ea=!1}b.Xa=(H.location.ancestorOrigins||[])[0];b.title=H.document.title||"";b.la="";b.ha=function(){function d(f,e,h){h?(f=(f+"").slice(h).lastIndexOf(e),-1!=f&&(f+=h)):f=(f+"").lastIndexOf(e);return 0<=f?f:!1}try{return b.la="1: parent.parent.location.href",H.parent.parent.location.href}catch(f){try{return b.la="2: parent.location.href",H.parent.location.href}catch(e){if(d(e.message,"<",0))return e.message.substring(d(e.message,"<",0)+1,d(e.message,">",0));b.la="3:  location.href";
return H.location.href}}}()||"";var c=b.ha;if(b.Ga){b.ha=H.document.referrer;b.la="6: top != window -> GLOBAL.document.referrer "+location.href;b.ea&&(b.ha=H.location.href,b.la="7: top != window & friendly -> GLOBAL.location.href "+document.referrer);"about:blank"==b.ha&&(b.ha=H.location.href);try{b.title=a.frameElement(H).id+"@"+location.href}catch(d){b.title="frame without title"}}""==b.ha&&(b.la="4: old_browser.uri_courant",b.ha=c);return b}
function Qb(){function a(){var d={},f={Flash:"ShockwaveFlash.ShockwaveFlash.1",PDF:"AcroPDF.PDF",Silverlight:"AgControl.AgControl",QuickTime:"QuickTime.QuickTime"};if(H.ActiveXObject){var e=function(n){try{var t=new ActiveXObject(n);try{return t.GetVariable("$version")}catch(p){try{return t.GetVersions()}catch(w){try{for(n=9;0<n;n--)if(t.isVersionSupported(n+".0"))return n}catch(C){}return!0}}}catch(p){return!1}};for(g in f){var h=e(f[g]);h&&(d[g]=h)}H.navigator.javaEnabled()&&(d.java="")}else{f.Java=
void 0;var g=H.navigator.plugins;for(e in g)for(h in f){var l=g[e].description;if(l&&-1!=l.indexOf(h)){var k=g[e].version;d[h.toLowerCase()]=k?k:g[e].name+" "+l}}}for(var q in d)f=/[0-9]+/.exec(d[q]),d[q]=f?f[0]:"";return d}var b=/^.* ([^ ]+)(.{2}) [^ ]+$/.exec(new Date);b=b?b.slice(1).join(":"):"";var c="";try{c=JSON.stringify(a())}catch(d){}return function(d){var f=0;if(!d.length)return f;for(var e=0;e<d.length;e++)f=(f<<5)-f+d.charCodeAt(e),f&=f;return f}(b+c)+function(){var d={monospace:void 0,
"sans-serif":void 0,serif:void 0},f="cursive;monospace;serif;sans-serif;fantasy;default;Arial;Arial Black;Arial Narrow;Arial Rounded MT Bold;Bookman Old Style;Bradley Hand ITC;Century;Century Gothic;Comic Sans MS;Courier;Courier New;Georgia;Gentium;Impact;King;Lucida Console;Lalit;Modena;Monotype Corsiva;Papyrus;Tahoma;TeX;Times;Times New Roman;Trebuchet MS;Verdana;Verona".split(";"),e=H.document.createElement("span");e.style.position="absolute";e.style.top=e.style.left="-1000px";e.style["font-size"]=
"72px";e.innerText="mmmmmmmmmmlli";H.document.body.appendChild(e);for(var h in d)e.style["font-family"]=h,d[h]=[e.offsetWidth,e.offsetHeight];h=f.length;a:for(;0<h--;){for(var g in d)if(e.style["font-family"]=f[h]+","+g,e.offsetWidth!=d[g][0]||e.offsetHeight!=d[g][1]){f[h]="t";continue a}f[h]="f"}H.document.body.removeChild(e);return f.join("")}()}function Ob(a){a=nb(a);a=a.protocol+"//"+a.host;var b=H.document.createElement("link");b.rel="preconnect";b.href=a;H.document.head.appendChild(b)}
function Pb(a,b){b?b.parentNode.insertBefore(a,b.nextSibling):(H.document.body||H.document.head).appendChild(a)}m.T=function(a){return L(a)?(a.textContent||a.innerText||"").trim():null};
m.ja=function(a,b,c){var d=c&&c["%b"]||null;if(d){var f="text/plain";c["%t"]&&(f=c["%t"],delete c["%t"]);d=new Blob([d],{type:f});delete c["%b"]}var e=this.url(a,b,c);if(e){b=function(){if(!a||a.ended||d){try{var g=new XMLHttpRequest;g.open(d?"POST":"GET",e,a?!a.ended:!0);g.send(d)}catch(l){return}return!0}};if(c=!function(){if(N(H.fetch)&&L(H.chrome)){var g={mode:"no-cors",cache:"no-cache",keepalive:!0};d&&(g.method="POST",g.body=d);H.fetch(e,g);return!0}}()){a:{if(N(H.navigator.sendBeacon))try{var h=
H.navigator.sendBeacon(e,d);break a}catch(g){}h=void 0}c=!h}c&&!b()&&((new Image).src=e)}};
m.Ha=function(a,b,c){function d(){f.ja(a,b,c);a.g=!1;a.l("fw",{state:a.g})}var f=this;c.appname=H.navigator.appName||"unknown";c.fai=this.s.title;c.iframe=this.s.Ga?this.s.ea?3:1:0;c.fake=function(){return""+~~f.s.ab+~~f.s.qb+~~f.s.rb+~~f.s.H+~~f.s.sb+~~(0==H.screen.height&&0==H.screen.width||0==H.devicePixelRatio)};c.resolution=H.screen.width+"x"+H.screen.height;c.nav_lang=H.navigator.language;c.debug=this.s.la;c.url_referrer=this.s.ha.substr(0,500);c.ao=this.s.Xa;try{c.nb_cpu=H.navigator.hardwareConcurrency}catch(k){}c.data=
Qb();a.j.activetab=function(){return~~f.S};if(a.ra){var e=function(k){if(!O(a.g)){a.g=!1;k=Xa(k)?k:"";if("%%BLOCK%%"==k.trim())a.g=!0;else if(k=k.split("\n").filter(function(t){return/^[\p{L}][\p{L}\p{Z}+]*$/u.test(t.trim())}),k.length){var q=function w(p){if(p){for(var C=[p],r=L(p.frames)?p.frames.length:0;0<r--;)C.push.apply(C,u(w(p.frames[r])));return C}}(H.top).reduce(function(p,w){try{p.push.apply(p,u(w.document.querySelectorAll("title,h1,h2,h3,h4,h5,h6,p")))}catch(C){}return p},[]).map(f.T).join("\n");
try{var n=(new RegExp(k.map(function(p){p=p.split("+");return 1<p.length?p.map(function(w){return"(?=.*\\b("+w.trim()+")\\b)"}).join(""):"\\b("+p[0].trim()+")\\b"}).join("|"),"ui")).exec(q);a.g=!!n;a.g&&(c.ads_forceblock=1,c.alerte_desc="keyword content:"+n.splice(1).filter(function(p){return p}).join("+"),f.ja(a,b,c))}catch(p){}}a.l("fw",{state:a.g})}},h=this.url(a,b,c);if(h){var g=function(){var k=String.fromCharCode(97+26*Math.random())+Math.random().toString(16).substr(2);Object.defineProperty(H,
k,{value:e.bind(this)});var q=H.document.createElement("script");q.src=h+"&jsonp="+k;q.setAttribute("data-adloox-sid",a.N);q.onerror=d.bind(this);Pb(q,V||H.document.head)};try{var l=new XMLHttpRequest;l.open("GET",h);l.onload=function(){if(4==l.readyState){if(400<=l.status)return g();e(l.responseText)}};l.onerror=g;l.ontimeout=g;l.timeout=5E3;l.send(null)}catch(k){g()}}}else d()};
m.url=function(a,b,c){if(b=X.prototype.url.call(this,a,b,c))return b.split("[ADL_DOM]").join(nb(this.s.Xa||H.origin).hostname||"")};function Rb(){function a(){a=J;b.start()}Y.call(this,"browser");var b=new Mb(this);this.V[b.N]=b;V&&V.setAttribute("data-adloox-sid",b.N);this.o=10;b.subscribe("start",this.F,this);"prerender"==H.document.visibilityState?H.document.addEventListener("visibilitychange",function(){a()},this.s.H?!1:{passive:!0,once:!0}):a();this.g()}v(Rb,Y);
Rb.prototype.ta=function(a,b,c){a.ra&&a.subscribe("impression",function(d){var f=d.I.v||H.document.body;"BODY"!=f.tagName||d.D.s.Ga||d.D.s.sa||(f=null);f&&(f.style.visibility=c.state?"hidden":"visible");d.audio.v&&(f.muted=c.state)});Y.prototype.ta.call(this,a,b,c)};
Rb.prototype.F=function(a){function b(){var g=d?c.s.ea?H.top.document.documentElement:void 0:Sb(c,a);g?(a.j.d6=d?"found-takeover":a.m.targetelt.length?"found-targetelt":"found-wabbit",a.l("adunit","VIDEO"==g.tagName?{video:g}:{slot:g})):null===g?(h++,a.j.d7=h,T(b,Math.min(5E3,h*h*200))):(a.j.d6="died",a.end())}var c=this,d=1==a.m.creatype,f=V?V.parentNode:null;if(!d&&!a.m.targetelt.length&&f){var e=/ celtra-ad-v[34] /.test(" "+f.className+" ")?f:f.querySelector(".celtra-ad-v3,.celtra-ad-v4");if(e){a.j.d6=
"hunt-celtra";f=function(){var g=e.celtra.viewabilityObservee;a.j.d6="found-celtra";a.l("adunit","VIDEO"==g.tagName?{video:g}:{slot:g})};(e.celtra||{}).loaded?f():e.addEventListener("celtraLoaded",f,this.s.H?!1:{passive:!0});return}}var h=0;a.j.d3=H.screen&&H.screen.width+"x"+H.screen.height||void 0;a.j.d6=d?"hunt-takeover":a.m.targetelt.length?"hunt-targetelt":"hunt-wabbit";a.j.d7=h;a.j.d8=a.m.targetelt.length&&""+a.m.targetelt||void 0;b()};
function Sb(a,b){function c(r){for(var x=[H],z=0;z<x.length;z++){var F,B=x[z];if(B){for(F=L(B.frames)?B.frames.length:0;0<F--;)-1==x.indexOf(B.frames[F])&&x.push(B.frames[F]);if(L(B.parent)&&B!=B.parent)for(F=L(B.parent.frames)?B.parent.frames.length:0;0<F--;)-1==x.indexOf(B.parent.frames[F])&&x.push(B.parent.frames[F])}}for(z=0;z<r.length;z++)for(F=0;F<x.length;F++){B=void 0;try{B=x[F].document}catch(E){}if(B&&B.body){var K=void 0;try{K=B.getElementById(r[z])}catch(E){K=null}if(K)return K;try{K=
B.body.getElementsByClassName(r[z])}catch(E){K=[]}if(K.length)return K[0];try{K=B.body.querySelector(r[z])}catch(E){K=null}if(K)return K}}return null}function d(r){function x(Ea){var ja=Math.log(a.o-K+2);ja*=ja;if(!z)return ja;var wb=h(F);Ea=h(Ea);!wb&&Ea?ja*=.2:wb&&!Ea&&(ja*=5);return ja}var z=null,F=null,B=null,K=a.o,E=r;if(E.ownerDocument.head.contains(E)){E=E.ownerDocument.body.lastChild;if(!E)return null;do E=E.previousSibling;while(E&&1!=E.nodeType)}var D=null,A=null,Q=null,R=null,ka=0,la=0;
do{if(!D&&!A&&E&&"BODY"!=E.tagName){D=A=Q=R=E;(E=E.parentNode)&&"BODY"==E.tagName&&(E=null);do A=A.nextSibling;while(A&&1!=A.nodeType)}if(D&&ka>=la){var sa=(Q=g(D))&&x(Q);!Q||z&&Q.width*Q.height/sa<F.width*F.height/B||!f(D,Q)||(z=D,B=sa,F=Q);Q=D;do D=D.previousSibling;while(D&&1!=D.nodeType);for(;D&&D.children&&D.children.length;)D=D.children[D.children.length-1],ka++}if(A&&la>=ka){sa=(R=g(A))&&x(R);!R||z&&R.width*R.height/sa<F.width*F.height/B||!f(A,R)||(z=A,B=sa,F=R);R=A;do A=A.nextSibling;while(A&&
1!=A.nodeType);for(;A&&A.children&&A.children.length;)A=A.children[0],la++}!D&&Q&&ka>=la&&((D=Q.parentNode)&&"BODY"==D.tagName&&(Q=D=null),ka--);!A&&R&&la>=ka&&((A=R.parentNode)&&"BODY"==A.tagName&&(R=A=null),la--)}while((D||A||E)&&0<K--);z||250!=a.o||"complete"!==r.ownerDocument.readyState||(z=void 0);a.o=Math.min(250,2*a.o);return z}function f(r,x){if(!Ya(r))return!1;switch(r.tagName){case "DIV":var z=r.style["background-image"];if(z&&!/^url\("?([^")]+)"?\)$/.test(z))break;case "SPAN":if(r.innerText&&
r.innerText.trim())break;case "ARTICLE":case "VIDEO":case "IMG":case "CANVAS":case "OBJECT":case "EMBED":case "SVG":case "IFRAME":case "INS":return"proxy"!=r.getAttribute("data-adloox-type")&&e(r,x)}return!1}function e(r,x){if(r.clientWidth+5<r.scrollWidth)return!1;x=x||a.wa(r);if(20>x.width||20>x.height)return!1;r=Cb(W(r));return 0<=x.top+r.y+5&&0<=x.left+r.x+5}function h(r){return!!{"390x220":1,"320x240":1,"320x250":1,"320x300":1,"600x400":1,"330x280":1,"320x100":1,"970x250":1,"320x50":1,"120x20":1,
"160x20":1,"210x30":1,"300x600":1,"300x1050":1,"970x90":1,"300x250":1,"180x150":1,"160x600":1,"720x90":1,"970x60":1,"120x60":1,"80x30":1,"600x250":1,"600x150":1,"600x600":1,"720x310":1,"550x480":1}[r.width+"x"+r.height]}function g(r){if(r=a.wa(r))r.width=10*(r.width/10|0),r.height=10*(r.height/10|0);return r}var l=V||H.document.body;try{if(b.m.targetelt.length)return c(b.m.targetelt);var k=l;try{for(;!e(k)&&W(k)!=H.top;){k=a.frameElement(k);if(!k)break;l=k}}catch(r){}k=null;k=d(l);var q=a.frameElement(l);
!k&&q&&(k=d(q));if(!k){var n=l.ownerDocument.body;n&&e(n)&&(k=n)}if(!k&&q){var t=q.ownerDocument.body;t&&e(t)&&(k=t)}if(k)for(var p=g(k);;){var w=k.parentNode;if(!w||!f(w))break;var C=g(w);if(!C||p.width!=C.width||p.height!=C.height)break;k=w}return k}catch(r){b.l("error",{err:r.message,"%b":r.stack}),b.j.d2=r.message}}
function Tb(){function a(){L(H.mraid)&&N(H.mraid.getState)?"loading"==H.mraid.getState()?H.mraid.addEventListener("ready",b):b():a.t=T(a,200)}function b(){c.l("MRAID.ready");c.O.mraid={version:H.mraid.getVersion(),type:H.mraid.getPlacementType(),env:H.MRAID_ENV};var d=H.mraid.getScreenSize();c.j.resolution=d.width+"x"+d.height;c.I.data({id:"mraid",$:!1});T(c.start,0)}Y.call(this,"mraid");this.o=this.F=null;var c=new Mb(this);this.V[c.N]=c;c.m.creatype=2;V&&V.setAttribute("data-adloox-sid",c.N);c.subscribe("start",
this.ya,this);a();this.g()}v(Tb,Y);Tb.prototype.ta=function(a,b,c){if(c.state)try{H.mraid.close(),H.mraid.close(),H.mraid.unload()}catch(d){}Y.prototype.ta.call(this,a,b,c)};
Tb.prototype.ya=function(a){var b=this;this.F="hidden"==H.mraid.getState();H.mraid.addEventListener("stateChange",function(c){a.l("MRAID.stateChange",c);b.F="hidden"==c;b.F&&a.l("send.visi");Ub(b,a)});3<=a.O.mraid.version?H.mraid.addEventListener("exposureChange",function(c){a.l("MRAID.exposureChange",c);b.o=c/100;Ub(b,a)}):(this.o=~~H.mraid.isViewable(),H.mraid.addEventListener("viewableChange",function(c){a.l("MRAID.viewableChange",c);b.o=~~c;Ub(b,a)}));Ub(this,a);a.l("adunit",{slot:H.document.documentElement})};
function Ub(a,b){b.I.data({id:"mraid",state:a.F,ratio:a.o})}
function Vb(){Y.call(this,"vpaid");var a=this;this.K=null;this.ka=[];this.Na=[];this.Za=this.va=this.Da=this.Ra=this.height=this.width=this.B=this.slot=this.G=null;this.version=2;this.Oa=Infinity;this.qa=this.Wa=null;this.Pa=this.skippable=!1;this.volume=null;this.F=0;this.M=function(d){(a.G==a.aa?a.K.l:J)(d)};this.Fa=[[.01,function(){return a.M("VPAID.AdVideoStart")}],[.25,function(){return a.M("VPAID.AdVideoFirstQuartile")}],[.5,function(){return a.M("VPAID.AdVideoMidpoint")}],[.75,function(){return a.M("VPAID.AdVideoThirdQuartile")}],
[.99,function(){return a.M("VPAID.AdVideoComplete")}]];this.Pa=!1;this.aa={resizeAd:function(d,f,e){this.width=d;this.height=f;this.Ra=e;this.K.l("geometry")},startAd:function(){this.aa.startAd=J;this.B.play()},stopAd:function(){this.aa.stopAd=J;this.K.end()},pauseAd:function(){this.B.pause()},resumeAd:function(){this.B.play()},expandAd:J,collapseAd:J,skipAd:function(){this.skippable&&(this.aa.skipAd=J,this.Pa=!0,this.G.stopAd.call(this.G))},getAdLinear:function(){return!0},getAdWidth:function(){return this.width},
getAdHeight:function(){return this.height},getAdExpanded:function(){return!1},getAdSkippableState:function(){return this.skippable},getAdRemainingTime:function(){return isFinite(this.B.duration)?this.B.duration-this.B.currentTime:-2},getAdDuration:function(){return isFinite(this.B.duration)?this.B.duration:-2},getAdVolume:function(){return isFinite(this.B.volume)?this.B.volume:1},setAdVolume:function(d){M(d)&&0<=d&&1>=d&&(this.B.volume=d)},getAdCompanions:function(){return this.Wa},getAdIcons:function(){return!1}};
for(var b in this.aa)this.aa[b]=this.aa[b].bind(this);this.o={handshakeVersion:function(d){d=P(d);1<=d&&2>=d&&(this.version=d);return this.version+".0"},initAd:function(d,f,e,h,g,l){function k(){n.qa&&p.l("VPAID.AdClickThru",n.T(n.qa),n.qa.id,!0)}function q(r,x){n.B.addEventListener(r,x,n.s.H?!1:{passive:!0});w.push([r,x])}var n=this,t=(((g||{}).AdParameters||"").match(/(?:^|.*&)vpaid=adloox(?:$|&.*)/)||[""])[0],p=new Mb(this,t);p.m.creatype=23;this.K=this.V[p.N]=p;V&&V.setAttribute("data-adloox-sid",
p.N);t&&("adparameters"in p.m?g.AdParameters=p.m.adparameters:delete g.AdParameters);this.width=d;this.height=f;this.Ra=e;this.Da=h;this.va=g;this.Za=l;p.O.vpaid={videoSlotCanAutoPlay:l.videoSlotCanAutoPlay};this.slot=l.slot;this.B=l.videoSlot;p.audio.data({id:"vpaid",$:!1});p.subscribe("VPAID.AdStarted",function(){n.volume=Wb(n)});for(d=this.ka.length;0<d--;)f=this.ka[d],p.subscribe(f.name,f.pa,f.context);p.start();p.subscribe("fw",function(r,x,z){z.state&&n.Z("adloox.com brand safety")});var w=
[];p.subscribe("end",function(){w.forEach(function(r){n.B.removeEventListener(r[0],r[1])})});q("loadedmetadata",function(){n.M("VPAID.AdLoaded");n.M("VPAID.AdDurationChange");q("durationchange",function(){n.M("VPAID.AdDurationChange")})});var C=!1;q("play",function(){C||(C=!0,n.M("VPAID.AdStarted"))});q("timeupdate",function(){2>n.version&&n.M("VPAID.AdRemainingTimeChange");!n.skippable&&n.B.currentTime>=n.Oa&&(n.skippable=!0,n.M("VPAID.AdSkippableStateChange"));var r=isFinite(n.B.duration)&&n.B.currentTime/
n.B.duration;n.Fa=n.Fa.filter(function(x){var z=M(x[0])?x[0]:Date.parse("1970-01-01 "+x[0]+"Z")/1E3/n.B.duration;if(r<z)return!0;x[1]();return!1})});q("playing",function(){C||(C=!0,n.M("VPAID.AdStarted"));p.l("rollstate.run");n.M("VPAID.AdPlaying")});q("pause",function(){n.B.ended||(p.l("rollstate.pause"),n.M("VPAID.AdPaused"))});q("volumechange",function(){Wb(n)});q("ended",function(r){r.G.stopAd()}.bind(this,this));q("error",function(){n.Z(n.B.error?n.B.error.message:"unable to load video")});this.slot.addEventListener("click",
k,this.s.H?!1:{passive:!0});p.subscribe("end",function(r){n.slot.removeEventListener("click",k);n.G==n.aa&&(delete n.B.src,delete n.B.preload,r.l(n.Pa&&2<=n.version?"VPAID.AdSkipped":"VPAID.AdStopped"))});p.l("adunit",{slot:this.slot,video:this.B});d=p.m.vast;"::"==d.substr(0,2)?(p.m.vast_clickthru&&(this.qa=document.createElement("p"),this.qa.textContent=p.m.vast_clickthru),d=Xb(this,p,d.substr(2))):d=":"==d.substr(0,1)?Yb(this,p,d.substr(1)):Zb(this,p,d);if(!d)return this.Z("unsuitable vast parameter")},
startAd:function(d){this.K.ra?this.K.subscribe("fw",function(f,e,h){h.state||d.G.startAd.call(d.G)}):d.G.startAd.call(d.G)}.bind(this,this),subscribe:function(d,f,e){function h(g,l,k){for(var q=[],n=2;n<arguments.length;++n)q[n-2]=arguments[n];d.apply(null,u(q))}h.$a=d;this.K?this.K.subscribe("VPAID."+f,h,e):(-1==this.Na.indexOf(f)&&this.Na.push(f),this.ka.unshift({name:"VPAID."+f,pa:h,context:e||this}))},unsubscribe:function(d,f){if(this.K)this.K.unsubscribe("VPAID."+f,d);else for(var e=this.ka.length;0<
e--;)this.ka[e].name=="VPAID."+f&&this.ka[e].pa.$a==d&&this.ka.splice(e,1)},resizeAd:J,stopAd:J,pauseAd:J,resumeAd:J,expandAd:J,collapseAd:J,skipAd:J,getAdLinear:J,getAdWidth:J,getAdHeight:J,getAdExpanded:J,getAdSkippableState:J,getAdRemainingTime:J,getAdDuration:J,getAdVolume:J,setAdVolume:J,getAdCompanions:J,getAdIcons:J};b={};for(var c in this.o)b.ia=c,this.o[b.ia]=this.o[b.ia]==J?function(d,f){for(var e=[],h=1;h<arguments.length;++h)e[h-1]=arguments[h];if(this.G){J.apply(null,["VPAID",d].concat(u(e)));
try{return this.G[d].apply(this.G,e)}catch(g){}}else J.apply(null,["VPAID (noop)",d].concat(u(e)))}.bind(this,b.ia):function(d){return function(f,e){for(var h=[],g=1;g<arguments.length;++g)h[g-1]=arguments[g];J.apply(null,["VPAID (wrapper)",d.ia].concat(u(h)));return f.apply(this,h)}}(b).bind(this,this.o[b.ia]),b={ia:b.ia};this.ya=function(){return this.o}.bind(this);this.g()}v(Vb,Y);
function Xb(a,b,c){a.G=a.aa;Wb(a);b.subscribe("impression",function(d){d.l("VPAID.AdImpression")});a.B.preload="metadata";a.B.src=a.url(b,Xa(c)?c:a.T(c));a.B.load();return!0}function Wb(a){var b=a.G.getAdVolume.call(a.G);0<a.volume&&0==b?a.M("VPAID.AdVolumeChange.mute"):0==a.volume&&0<b&&a.M("VPAID.AdVolumeChange.unmute");a.volume=b;a.M("VPAID.AdVolumeChange");a.K.audio.data({id:"vpaid",ratio:a.volume,muted:0==a.volume});return b}
function $b(a,b,c,d,f,e){for(var h=H.navigator.connection?1E3*H.navigator.connection.downlink:5E4,g=[],l=0;l<c.length;l++){var k=c[l];if(!k.getAttribute("apiFramework")){var q=k.getAttribute("type");if(q){var n=k.getAttribute("codec");n&&(q+=';codecs="'+n+'"');if(a.B.canPlayType(q)){var t=k.getAttribute("width"),p=k.getAttribute("height");t&&p&&(q="true"==(k.getAttribute("scalable")||"false").toLowerCase(),n="true"==(k.getAttribute("maintainAspectRatio")||"true").toLowerCase(),(d||q||t==a.width&&
p==a.height)&&!(!f&&q&&1<t*p/(a.width*a.height))&&(t=a.width/t/(a.height/p),f||!q||!n||.95<=t&&1.05>=t))&&(q=Math.max(k.getAttribute("bitrate"),k.getAttribute("maxBitrate")),h<q||!e&&0<a.Da&&q>a.Da||g.push(k))}}}}g=g.sort(function(w,C){w=Math.max(w.getAttribute("bitrate"),w.getAttribute("maxBitrate"));C=Math.max(C.getAttribute("bitrate"),C.getAttribute("maxBitrate"));return e?w-C:C-w});h=g[0];for(l=1;l<g.length;l++)k=h.getAttribute("width"),q=h.getAttribute("height"),n=g[l].getAttribute("width"),
t=g[l].getAttribute("height"),1-Math.abs(n*t/(a.width*a.height))<1-Math.abs(k*q/(a.width*a.height))&&(h=g[l]);return h?Xb(a,b,h):d&&f&&e?!1:$b(a,b,c,!0,!!d,!!f)}
function Yb(a,b,c,d){d&&(a.va=d.querySelector("AdParameters"),a.va={AdParameters:a.T(a.va)||void 0});var f=document.createElement("iframe");f.src="javascript:false";f.style.display="none";f.onload=function(){var e=document.createElement("script");e.src=a.url(b,c);e.onload=function(){var h=f.contentWindow.getVPAIDAd;if(!N(h))return a.Z("VPAID unit has no getVPAIDAd");a.G=h();b.subscribe("VPAID.AdSkipped",b.end);b.subscribe("VPAID.AdStopped",b.end);b.subscribe("VPAID.AdVideoFirstQuartile",function(){b.l("send.visi")});
b.subscribe("VPAID.AdVideoMidpoint",function(){b.l("send.visi")});b.subscribe("VPAID.AdVideoThirdQuartile",function(){b.l("send.visi")});b.subscribe("VPAID.AdVideoComplete",function(){b.l("send.visi")});var g=!1,l=!1,k=null;b.subscribe("VPAID.AdVideoThirdQuartile",function(q){k=eb(function(){l=2>a.G.getAdRemainingTime.call(a.G)},500);q.subscribe("VPAID.AdVideoComplete",function(n){db(k);l=!1;g&&n.l("VPAID.AdStopped")})});a.Na.forEach(function(q){"AdStopped"==q?a.G.subscribe.call(a.G,function(){g=
!0;l||(k&&db(k),b.l("VPAID.AdStopped"))},q,a):a.G.subscribe.call(a.G,b.l.bind(a,"VPAID."+q),q,a)});a.G.initAd.call(a.G,a.width,a.height,a.Ra,a.Da,a.va,a.Za)};f.contentWindow.document.head.appendChild(e)};Pb(f,V);return!0}function ac(a,b,c,d){if(d=d&&d.getAttribute("skipoffset"))a.Oa=Date.parse("1970-01-01 "+d+"Z")/1E3,b.O.vpaid.skipoffset=a.Oa;(b=c.querySelector("ClickThrough"))&&/^https?:/.test(a.T(b))&&(a.qa=b)}
function bc(a,b,c,d){var f={skip:"AdSkipped",creativeView:"AdStarted",start:"AdVideoStart",firstQuartile:"AdVideoFirstQuartile",midpoint:"AdVideoMidpoint",thirdQuartile:"AdVideoThirdQuartile",complete:"AdVideoComplete",pause:"AdPaused",resume:"AdPlaying",Impression:"AdImpression",ClickTracking:"AdClickThru",Error:"AdError",mute:"AdVolumeChange.mute",unmute:"AdVolumeChange.unmute"};[].concat(u(c.querySelectorAll("Tracking,Impression,ClickTracking,Error,Viewable,NotViewable,ViewUndetermined"))).forEach(function(g){var l=
a.T(g);if(/^https?:/.test(l)){var k=function(){b.l("send",a.url(b,l))},q=g.getAttribute("event")||g.tagName;switch(q){case "progress":d&&(g=(g.getAttribute("offset")||"").trim(),"%"==g.substr(-1)?a.Fa.push([P(g.substr(0,g.length-1))/100,k]):/^[0-9:]+$/.test(g)&&a.Fa.push([g,k]));break;case "Viewable":b.Ca("px_view",a.T(g));break;case "NotViewable":b.Ca("px_viewn",a.T(g));break;case "ViewUndetermined":b.Ca("px_viewu",a.T(g));break;default:(g=f[q])&&b.subscribe("VPAID."+g,k)}}});c=c.querySelectorAll("Survey");
for(var e=0;e<c.length;e++){var h=a.T(c[e]);/^https?:/.test(h)&&b.Ca("js_imp",h)}}
function Zb(a,b,c,d){var f=new XMLHttpRequest;f.open("GET",a.url(b,c));f.withCredentials=!d;f.onload=function(){if(4==f.readyState){if(400<=f.status)return a.Z.call(a,"failed to fetch VAST");a:{var e=f.responseXML;if("VAST"!=e.documentElement.tagName)var h=a.Z("not a VAST tag");else{h=!a.F&&b.m.vast_skiptracking;var g=[],l=[];e=e.querySelectorAll("Ad");for(var k=0;k<e.length;k++){var q=e[k],n=q.getAttribute("sequence");n?(n=P(n),0<n&&(g[n]=q)):l.push(q)}g=g.concat(l);for(l=0;l<g.length;l++)if(e=g[l]){if(k=
e.querySelector("VASTAdTagURI")){ac(a,b,e);h||bc(a,b,e);h=5>a.F++?Zb(a,b,a.T(k)):a.Z("too many wrappers");break a}a.Wa=(e.querySelector("CompanionAds")||{}).outerHTML;k=e.querySelector("Creatives").querySelectorAll("Creative");for(q=0;q<k.length;q++)if(n=e.querySelector("Linear")){ac(a,b,e,n);h||bc(a,b,e,n);var t=n.querySelectorAll("MediaFiles > MediaFile"),p=n.querySelector("MediaFiles > MediaFile[apiFramework='VPAID'][type='application/javascript']");if(p&&Yb(a,b,a.T(p),n)||$b(a,b,t)){h=!0;break a}}}h=
!1}}if(!h)return a.Z.call(a,"VAST returned nothing usable")}};f.onerror=function(){if(d)return a.Z.call(a,"unable to download VAST");Zb(a,b,c,!0)};f.ontimeout=a.Z.bind(a,"timeout downloading VAST");f.timeout=5E3;f.send(null);return!0}Vb.prototype.Z=function(a){this.K.l("VPAID.AdError",a);this.K.end()};
function cc(){X.call(this,"omid");var a=this;Ma(function(b){switch(b.type){case "sessionStart":var c=new Mb(a,b.data.verificationParameters);c.m.creatype=0;a.V[b.adSessionId]=c;c.data={context:b.data.context};V&&V.setAttribute("data-adloox-sid",c.N);a.Va(b);default:try{a.Ua(b)}catch(d){a.V[b.adSessionId].l("error",{err:"omid: "+d.message,"%b":d.stack})}}});this.g()}v(cc,X);m=cc.prototype;
m.Ua=function(a){var b=this.V[a.adSessionId],c=a.data,d=b.data.context;b.l("OMID."+a.type,a);switch(a.type){case "sessionStart":var f=function(h){return Xa(h)&&!h.length?void 0:h};b.O.omid={};["impressionType","creativeType","mediaType","pageUrl","contentUrl"].forEach(function(h){return b.O.omid[h]=f(c[h])});"apiVersion environment accessMode adSessionType omidNativeInfo omidJSInfo app deviceInfo".split(" ").forEach(function(h){return b.O.omid[h]=f(d[h])});"app"==d.environment&&(b.j.appname=d.app.appId);
b.I.data({id:"omid",$:!1});b.audio.data({id:"omid",$:!1});break;case "sessionError":b.l("error",{err:"omid","%b":a.data.message});break;case "sessionFinish":b.end();break;case "loaded":switch(c.creativeType){case "audio":case "video":b.m.creatype=6;break;default:b.m.creatype=2}b.O.omid.autoPlay=a.data.autoPlay;b.O.omid.skipOffset=a.data.skipOffset;b.O.omid.position=a.data.position;b.O.omid.duration=a.data.duration;break;case "impression":if(!b.m.creatype)switch(c.mediaType){case "video":b.m.creatype=
6;break;default:b.m.creatype=2}6!=b.m.creatype||b.data.audio||b.audio.data({id:"omid",U:!0,ratio:1});case "geometryChange":this.Ia(b,a);L(c.adView)&&(b.l("geometry",{width:c.adView.geometry.width,height:c.adView.geometry.height,top:c.adView.geometry.y,left:c.adView.geometry.x}),b.I.data({id:"omid",U:!0,ratio:c.adView.percentageInView/100}));break;case "start":this.Ia(b,a);case "volumeChange":var e=function(h){h=Math.max(0,Math.min(1,h));return isNaN(h)?1:h};b.audio.data({id:"omid",U:!0,ratio:e(a.data.mediaPlayerVolume)*
e(a.data.videoPlayerVolume)*e(a.data.deviceVolume)});b.data.audio=!0;break;case "resume":b.l("rollstate.run");break;case "pause":b.l("rollstate.pause")}};
m.Ia=function(a,b){this.Ia=J;b=b.data;var c={};switch(b.creativeType){case "audio":break;default:var d;(d=!L(b.adView)||-1!=b.adView.reasons.indexOf("notFound"))||(d=b.viewport,d=!(L(d)&&0<d.width*d.height));if(d)return;c.slot=a.data.context.slotElement;c.video=a.data.context.videoElement;b.adView&&(c.rect=b.adView.geometry);"limited"==a.data.context.accessMode&&(a.j.resolution=b.viewport.width+"x"+b.viewport.height)}a.start();a.l("adunit",c)};
m.Va=function(a){function b(h){return c(h)}function c(h){for(var g=f.length;0<g--;){var l=f[g][0].timestamp;if(l==h.timestamp){f[g].unshift(h);return}if(l>h.timestamp)break}f.splice(g+1,0,[h])}var d=this;this.Va=J;U(null,"impression",function(h){(h.m.js_imp||[]).forEach(function(g){Pa(this.url(h,g))})});var f=[],e=a.data.context;-1!=e.supports.indexOf("vlid")&&G.addEventListener(a.data.creativeType?"media":"video",b);"limited"!=e.accessMode&&-1==e.supports.indexOf("clid")||G.addEventListener("geometryChange",
b);G.addEventListener("impression",b);T(function(){c=d.Ua.bind(d);f=f.reduce(function(g,l){return g.concat(l)},[]);for(var h=f.length;0<h--;)c(f[h])},0)};m.ja=function(a,b,c){c&&c["%b"]&&(c.body=c["%b"],delete c["%b"]);(a=this.url(a,b,c))&&Na(a)};m.Ha=function(a,b,c){var d=this,f=this.url(a,b,c);if(f){var e=function(){a.l("fw",{state:!1});d.ja(a,b,c)};a.ra?Pa(f,function(){},e):e()}};
m.url=function(a,b,c){if(b=X.prototype.url.call(this,a,b,c))return b.split("[ADL_DOM]").join(nb(a.O.omid.pageUrl||a.O.omid.contentUrl||"").hostname||"")};var Z=null;function dc(){delete H.getVPAIDAd;Z=J;Z=new Vb;return Z.ya()}function ec(){H.getVPAIDAd==dc&&delete H.getVPAIDAd;Z||(L(H.MRAID_ENV)||L(H.mraid)?(Z=J,Z=new Tb):(Z=J,Z=new Rb))}function fc(){T(function(){T(ec,0)},0)}if(G)try{Z=new cc}catch(a){}
Z||(I?(N(H.getVPAIDAd)||(H.getVPAIDAd=dc),"loading"===H.document.readyState?H.document.addEventListener("DOMContentLoaded",fc,!1):fc()):Z=new X);}).call(this);
//# sourceMappingURL=tfav_adl_435.js.map
