[build]
  command = "hugo --gc --minify"
  publish = "/public"

[build.environment]
  HUGO_VERSION = "0.85.0+extended darwin/amd64"
[context.production.environment]
  HUGO_VERSION = "0.85.0+extended"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.85.0+extended"